"""empty message

Revision ID: 22520a2b33cd
Revises: 58663e8e86ff
Create Date: 2025-05-31 15:11:48.683471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22520a2b33cd'
down_revision = '58663e8e86ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.String(), nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('subject')

    # ### end Alembic commands ###
