"""empty message

Revision ID: f67acf29e393
Revises: 22520a2b33cd
Create Date: 2025-05-31 15:12:33.769139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67acf29e393'
down_revision = '22520a2b33cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.drop_column('subject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
